### ISSUE TITLE
Ignored `-std=c++17` on Mac OS X

### ISSUE THREAD

**Issue by genos** [j2kun/mlir-tutorial#10]
First off, thank you _very_ much for this tutorial! I've been meaning to pick up both `bazel` and MLIR, so this is extremely helpful.

One thing I stumbled over in getting set up: apparently, `bazel` [automatically detects XCode and picks a different toolchain](https://stackoverflow.com/a/47634361), which led to it ignoring the `-std=c++17` setting. Exporting `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1` in my shell ensured that the setting went through. I thought I'd share to save others the trouble I went through.

Thanks again!

**Comment by abhaikollara** [comment]
> First off, thank you _very_ much for this tutorial! I've been meaning to pick up both `bazel` and MLIR, so this is extremely helpful.
> 
> One thing I stumbled over in getting set up: apparently, `bazel` [automatically detects XCode and picks a different toolchain](https://stackoverflow.com/a/47634361), which led to it ignoring the `-std=c++17` setting. Exporting `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1` in my shell ensured that the setting went through. I thought I'd share to save others the trouble I went through.
> 
> Thanks again!

In case it's helpful, you can also add it into the `.bazelrc` along with the other env like this

```
build --action_env=BAZEL_CXXOPTS=-std=c++17 --action_env=BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
```

**Comment by steeve** [comment]
I use this with success ```
build       --cxxopt='-std=c++17'
build       --host_cxxopt='-std=c++17'
```

**Comment by j2kun** [comment]
I tried putting both the env and the cxxopt flags in

https://github.com/j2kun/mlir-tutorial/commit/5d097164d4ca4329cf020f54ef80731b32dd999b

@genos would you have a chance to test it? I don't have a mac to try it on.

**Comment by genos** [comment]
Interestingly, putting the environment flag in my `.bazelrc` (after removing it from my `~/.zshrc`) didn't work, but putting the other pieces in did. That is, the following `.bazelrc` works for me:

```
build --action_env=BAZEL_CXXOPTS=-std=c++17
build --cxxopt='-std=c++17'
build --host_cxxopt='-std=c++17'
test --test_output=all
```

**Comment by j2kun** [comment]
Thanks! Marking as fixed.

**Comment by genos** [comment]
@j2kun Just remembered I've got another change needed to get things working on 🍎 silicon; I'll open a new issue to cover it. See (or feel free to ignore!) #11.
