### ISSUE TITLE
Apple silicon requires an additional `_LLVM_TARGETS`

### ISSUE THREAD

**Issue by genos** [j2kun/mlir-tutorial#11]
Hi again! I hope that my issue raising comes across as intending to help rather than complain; _please_ let me know if I get too noisy/annoying!

In order to get everything to build on my M1 Mac, I needed to add `"AArch64"` to the `_LLVM_TARGETS` list in `bazel/setup_llvm.bzl`. Perhaps this step is obvious to those more in the know, but I wasn't sure of the exact string to put in to get things to build at first (`"darwin-arm64"`?).

Thanks again for this tutorial!

**Comment by j2kun** [comment]
No worries, I'll go ahead and add this by default.

**Comment by j2kun** [comment]
Fixed by https://github.com/j2kun/mlir-tutorial/commit/5eb372efce37219e0f4ee1a5f354cb03b50640cd
